#!/bin/bash

function help {
    whiptail --title "rvsh - Aide" --ok-button "Fermer" --msgbox "Aide pour la commande rvsh\n\n–connect <HOST> <USER> : Se connecter à la machine HOST avec l'utilisateur USER.\n–admin                 : Gestion des machines connectées au réseau virtuel et la liste des utilisateurs." 11 84 3>&1 1>&2 2>&3
}

function admin {
    echo -n "rvsh > "
    read cmd
    case "$cmd" in
	host ) create_host;;
    esac
}

function create_database {
    sqlite3 database.db "CREATE TABLE users (login TEXT PRIMARY KEY,nom TEXT,prenom TEXT,passwd TEXT);"
    sqlite3 database.db "CREATE TABLE hosts (hostname TEXT PRIMARY KEY);"
    sqlite3 database.db "CREATE TABLE grants (id INT PRIMARY KEY,login TEXT,hostname TEXT,adminallowed BOOLEAN,FOREIGN KEY(login) REFERENCES users(login),FOREIGN KEY(hostname) REFERENCES hosts(hostname));"
}

function create_host {
    hostname=''
    while [[ $hostname = '' ]]
    do
	hostname=$(whiptail --inputbox "Entrez le nom de la machine (hostname) : " 8 78 --title "rvsh - Créer une machine virtuelle" 3>&1 1>&2 2>&3)
    done
    #sqlite3 database.db "INSERT INTO hosts (hostname) VALUES ('${hostname}');"
}

function create_user {
    nom=$(whiptail --inputbox "Entrez le nom de l'utilisateur : " 8 78 --title "rvsh - Créer un compte utilisateur" 3>&1 1>&2 2>&3)
    prenom=$(whiptail --inputbox "Entrez le prénom de l'utilisateur : " 8 78 --title "rvsh - Créer un compte utilisateur" 3>&1 1>&2 2>&3)
    login=''
    while [[ $login = '' ]]
    do
	login=$(echo "`echo -n "${nom}" | tr 'A-Z' 'a-z' | cut -c 1-8``echo -n "${prenom}" | tr 'A-Z' 'a-z' | cut -c 1-2`")
	login=$(whiptail --inputbox "Entrez l'identifiant de l'utilisateur (login) : " 8 78 ${login} --title "rvsh - Créer un compte utilisateur" 3>&1 1>&2 2>&3)
    done
    passwd1='a'
    passwd1='b'
    while [[ $passwd1 != $passwd2 ]]
    do
	passwd1=''
	while [[ $passwd1 = '' ]]
	do
	    passwd1=$(whiptail --passwordbox "Entrez le mot de passe (passwd) : " 8 78 --title "rvsh - Créer un compte utilisateur" 3>&1 1>&2 2>&3)
	done
	passwd2=''
	while [[ $passwd2 = '' ]]
	do
	    passwd2=$(whiptail --passwordbox "Confirmez le mot de passe (passwd) : " 8 78 --title "rvsh - Créer un compte utilisateur" 3>&1 1>&2 2>&3)
	done
    done
    hash=$(echo -n ${passwd1} | sha512sum | awk '{ print $1 }')
    sqlite3 database.db "INSERT INTO users (login, nom, prenom, passwd) VALUES ('${login}','${nom}','${prenom}','${hash}');"
}

function connect {
    echo "Hello"
}

if [ ! -f 'database.db' ]
then
    create_database
fi

create_user

exit 0
